--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/mbere/Documents/FpChip8/TD/al_ip/ram_dual_ip.vhd
 -- Date	:	2021 03 08
 -- TD version	:	4.6.18154
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram_dual_ip IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	wea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	dob	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	web	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END ram_dual_ip;

ARCHITECTURE struct OF ram_dual_ip IS

	BEGIN

	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_A	=> 12,
			ADDR_WIDTH_b	=> 12,
			DATA_DEPTH_A	=> 4096,
			DATA_DEPTH_B	=> 4096,
			MODE		=> "DP",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "32K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> '1',
			ceb	=> '1',
			ocea	=> '0',
			oceb	=> '0',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> '0',
			rstb	=> '0',
			doa	=> doa,
			dob	=> dob
		);

END struct;
